### Manifest generated by Tres.
### 
### Add your libraries below, as per Sprockets rules -> https://github.com/sstephenson/sprockets

### Core dependencies 
#= require jquery-1.8.0.min
#= require underscore-min
#= require backbone-min
#= require tres

### This automagically makes all templates available in a window.JST object 
#= require templates

### Automatically require all scripts in assets/javascripts/screens, so generators 
### "just work"
#= require_tree ./screens

### Sample app file that includes a home screen. Change this at your leisure
#= require app