## Manifest generated by Tres.
## 
## Add your libraries below, as per Sprockets rules -> https://github.com/sstephenson/sprockets

## Core dependencies ##
#= require jquery-1.8.0.min
#= require underscore-min
#= require backbone-min
#= require tres

## Your stuff goes below this line ##