## Manifest generated by Tres.
## 
## Add your libraries below, as per Sprockets rules -> https://github.com/sstephenson/sprockets

## Core dependencies ##
#= require jquery-1.8.0.min
#= require underscore-min
#= require backbone-min
#= require tres

# Sample app file that includes a home screen. Change this at your leisure.
#= require screens/home
#= require app

## Your stuff goes below this line ##